Korrigiere Symbole für diverse Suchergebnistypen
codeformuenster/muenster-dashboard pull request #54
Opened 2019-02-19 21:07 UTC by thunfischtoast

Container, Recyclinghöfe, Sportstätten, Wickeltische usw. sollten nun in der Suchübersicht richtig angezeigt werden.

2019-02-20 19:15 UTC, ubergesundheit requested changes
Insgesamt wohl iO. Liest sich aber irgendwie nach sehr viel dupliziertem jsx.. Müsste das nicht auch mit weniger gehen?

2019-02-20 19:15 UTC, ubergesundheit commented on src/Components/SearchResultDetailled.tsx
> +    // console.log('Rendering pool search result');
Könnte auch komplett weg

2019-02-20 19:15 UTC, ubergesundheit commented on src/Components/SearchResults/SearchResultsAgency.tsx
> +    // console.log('Rendering pool search result');
Könnte auch komplett weg

2019-02-20 19:15 UTC, ubergesundheit commented on src/Components/SearchResults/SearchResultsDefault.tsx
> +function capitalizeFirstLetter(word: String) {
Funktioniert, köntte aber schöner gemacht werden

Gerne auch ruhig `const` oder `let` für `firstLetter` verwenden.

Der Ternary macht auch gar nicht so viel Sinn, oder? Wenn `word` ein String ist, dann sollte index 0 davon doch niemals falsy sein?!

Ich denke eine einfachere Version dieser Funktion könnte so aussehen: (ungetestet)
```javascript
function capitalizeFirstLetter(word: String) {
  if (!word) {
    return;
  }
  const [firstLetter, ...rest] = word.split('');
  return [firstLetter.toUpperCase(), ...rest].join('');
}
```

2019-02-21 12:02 UTC, thunfischtoast commented on src/Components/SearchResultDetailled.tsx
> +    // console.log('Rendering pool search result');
> Insgesamt wohl iO. Liest sich aber irgendwie nach sehr viel dupliziertem jsx.. Müsste das nicht auch mit weniger gehen?

Definitiv. Dieser PR erweitert im Grunde die bisherige, holprige Lösung um einige Subklassen, da sonst bei einigen Markertypen (z.B. Amt) bisher nichts bzw. fälschlicherweise das Schwimmbad-Symbol angezeigt wurde. Vielleicht schaff ich es bis nächste Woche die Suchergebnisse nochmal ganz zu refactoren. Danke für den Input!

2019-03-05 20:58 UTC, merged